### ISSUE TITLE
Create tool-tips on mouse-over bubbles

### ISSUE THREAD

**Issue by aspiers** [HackBrexit/MinistersUnderTheInfluence#104]
## Acceptance Criteria
This story can be considered done when:

**Given** a view of the front-end which shows bubbles representing frequency of meetings with a certain person / government office / organization,

**When** I move the mouse over a bubble in the UI

**Then** it should display a tooltip which shows what/who that particular bubble refers to, and how many meetings there were.

**Comment by chrisyeoward** [comment]
I'll have a crack at that this week, are we just presenting the title of the bubble's object and number of meetings?
