### ISSUE TITLE
Send Google Organisation formatted data to the API

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#106]
### Description
Correctly formatted ministerial meetings with Google data, following same format as @Greatlemer. Use this to send the CSV file to the API & generate more bubbles!

#### Comments, Questions and Considerations
You can download the formatted file [here](https://docs.google.com/spreadsheets/d/1K0xxnqlCuL0Wfe3JcJxWwQk9JAt4Q-vgzN4kBr-3a84/edit?usp=sharing).

### Acceptance Criteria
This story can be considered done when:
The file has been sent to the API  & visualised in the D3 bubbles.

**GIVEN**
The files can be sent to the API.

**WHEN** 
Ideally to be completed in advance of 14th January. 

**THEN** 
Visualise in D3 bubbles for the showcase on 24th January at the latest.

**Comment by aspiers** [comment]
I have exported this as CSV and tried importing via `push_data.py` but it didn't work even after munging the date formats to YYYY-MM.  Needs further investigation.

**Comment by charlottebrf** [comment]
I will cross check my data format alongside @Greatlemer BAE to see if I've done something inconsistent.
