### ISSUE TITLE
zero byte files

### ISSUE THREAD

**Issue by oskarpearson** [HackBrexit/MinistersUnderTheInfluence#11]
Hi

There are some zero-byte files in the repo: I was wondering if they were accidentally not committed correctly and are required?
- combinedmeetings.csv
- parse.js

Thanks!

Oskar

**Comment by charlottebrf** [comment]
Thanks for this, @elischutze any idea?

**Comment by elischutze** [comment]
I think we're waiting to merge the last pull request from the hackathon but i'll look into it. @charlottebrf I think only you have write access currently? Maybe you could pop me in there too so I can take a look

**Comment by eddiejaoude** [comment]
@elischutze the repo was not added to the **MinistersUnderTheInfluence**, you should now have full access. Any issues let us know.

Or if anyone else needs to be added to the team

**Comment by charlottebrf** [comment]
@elischutze you should have full access- can you let me know if you don't?

**Comment by elischutze** [comment]
@charlottebrf  I think the pull request has now been merged and those files should no longer be 0

move to close this issue
