### ISSUE TITLE
Epic 6: Visualise data in graph

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#19]
- Create D3 or C3 Force chart

**Comment by eddiejaoude** [comment]
If get the data in to **Elastic** (it has an API), then could use **Kibana** to display the data graphically https://www.elastic.co/products/kibana

**Comment by charlottebrf** [comment]
@sikesLpp @elischutze @jo-osborne @soosa -I think this sounds like a good idea what do you think?

**Comment by elischutze** [comment]
Not sure, @eddiejaoude will Kibana play well with our data?

**Comment by eddiejaoude** [comment]
Can manipulate the data to store in Elastic (json document store, copy of your DB), then Kibana can read from that. Just an idea

**Comment by elischutze** [comment]
sounds good on paper! remind me to take a deeper look at it in a week or
two 👌
