### ISSUE TITLE
Example of google doc for sorted orgs from hackathon: 

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#20]
https://docs.google.com/a/entrepreneurfirst.org.uk/spreadsheets/d/1aKDkCXnAohG213gmgxXttdDeBDXKadzor8aXkr5EwHA/edit?usp=sharing

**Comment by eddiejaoude** [comment]
The link does not work. It has `entrepreneurfirst` in the link, is that correct?

**Comment by charlottebrf** [comment]
@eddiejaoude  it does work it's that the sharing settings aren't open for anyone to view. You can either request access or I open to view for anyone on the link. What do you think is best?

**Comment by eddiejaoude** [comment]
I am not sure what sort of data. I will take a look.
