### ISSUE TITLE
Document restful API

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#41]
Data structure Readme & examples of how to write into it & API end points- get interface defined.

**Comment by eddiejaoude** [comment]
I heard this is blocking people, can we make this a **high** priority.

Include:
- End points
- Method & Request / Response json examples

**Comment by elischutze** [comment]
we have a bit of json format docs here: http://en.staging.meetings.vidhya.tv/api/v1/docs but it's not ideal re: endpoints. Maybe we could set up one of those API doc tools? That might be a fun task for someone
