### ISSUE TITLE
Separate date info into Day, Month and Year fields

### ISSUE THREAD

**Issue by jo-osborne** [HackBrexit/MinistersUnderTheInfluence#61]

**Comment by jo-osborne** [comment]
At the moment our datanormaliser puts dates into a string in the format "XXXX-XX-XX". It would be better to split these out into three separate fields, `[Year, Month, Date]`. Better yet, this could be a dict eg:

```
{
'year': 2011
'month': 01
'date': None
}
```

_or_ a class even. Let's find something nice!

**Comment by elischutze** [comment]
can we make it 'year' 'month' 'day' (instead of 'date'?)

**Comment by jo-osborne** [comment]
@elischutze yes of course! The above was simply to give @lucetzer a starting point. I have deliberately left it a bit open to allow her to research and choose an appropriate data structure - I'm sure she will be happy to change the 'date' field name to 'day'.
