### ISSUE TITLE
React: Create Utilities that can query the API to return an object of data.

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#74]

**Comment by aspiers** [comment]
Not sure whether this is something extra on top of what was done in #102?  All the API retrieval and parsing code is currently in `d3Chart.js`.  It might make sense to extract that into a separate data processing library file, although the processing is specific to our d3 visualisation ...

**Comment by charlottebrf** [comment]
@aspiers Is this still open then?

**Comment by aspiers** [comment]
For now these utilities are simply functions in `d3Chart.js` which utilise [`d3.request`](https://github.com/d3/d3/blob/master/API.md#requests-d3-request) to talk to the JSON API, and I think it makes sense to keep them like that.  If later we want other react components to query the API then we can think about extracting out any code not specific to the `Chart` component, but for now it's fine.
