### ISSUE TITLE
Take a processed row and push that data through to the API

### ISSUE THREAD

**Issue by Greatlemer** [HackBrexit/MinistersUnderTheInfluence#82]
### Description
After having processed a row:
Use the minister data to generate/lookup the id of the minister (using type 'person')
Use the minsters job role data to generate/lookup the id of the government office (using type 'government-office')
Use the organisation/participant column to generate/lookup the ids of the organisations and their representatives (using type 'organisation'/'person')
Use the date range and purpose data to generate a meeting id (using type 'meeting')

Combine the minister, government office and meeting ids to create a 'influence-government-office-people' entry

For each other participant combine the participant, organisation, and meeting ids to create a 'influence-organisation-people' entry

#### Comments, Questions and Considerations
Using http://en.staging.meetings.vidhya.tv/api/v1/docs for reference on what needs to be sent

### Acceptance Criteria
This story can be considered done when:

Given I have a row of data with a minister who is not yet in the database
When I have pushed the data to the API
Then it uses the logic described above

**Comment by charlottebrf** [comment]
Where are you at with this one @Greatlemer @jo-osborne

**Comment by aspiers** [comment]
@Greatlemer is this now resolved by the existence `push_data.py`?

**Comment by Greatlemer** [comment]
This is what that script does, but it's something that will be needed for the automated process.

**Comment by Greatlemer** [comment]
@aspiers after our discussion last night I'm thinking this can maybe be closed in favour of using the `push_data.py` script for now (as you suggested previously). We can re-evaluate later perhaps how we would like it to work as an automated step. Does that sound reasonable?

**Comment by aspiers** [comment]
@Greatlemer Yes good plan - IMHO we don't want to fully automate the push until we have made a lot more progress on data cleansing, and personally I'd prefer the github issues to focus more (although not exclusively) on the short-term than on the long-term.
