### ISSUE TITLE
Retrieve list of organisations from real data set

### ISSUE THREAD

**Issue by chrisyeoward** [HackBrexit/MinistersUnderTheInfluence#86]
### Description
We need to categorise the organisations.
Retrieve list of all organisations from REAL data, such that they can be organised. (issue #73)

#### Comments, Questions and Considerations
Include any relevant information

### Acceptance Criteria
This story can be considered done when:

**GIVEN**

**WHEN** 

**THEN** 
We have a list of all organisations existing in our data

**Comment by Greatlemer** [comment]
I modified the php script to fetch data from all the ministerial departments then ran a script over the files fetched (trying to single out the meeting ones) I'll check the script in on a branch later on, but I thought for now I'd post up the findings. First column is the (mostly) unprocessed organisation name and the second column is the number of times that exact organisation name was seen. I think the data goes back to 2010 in some cases.
 
[orgs.xlsx](https://github.com/HackBrexit/MinistersUnderTheInfluence/files/605187/orgs.xlsx)

**Comment by Greatlemer** [comment]
I've added the script to a branch and made a pull request for it now. Looking at the output there's a lot of work that we're going to have to do to tidy up the organisation list and there are definitely cases that may not be automatically separable such as:
"Arts Council England, Bolton & Quinn, Serpentine Gallery, Sage Gateshead, Baltic Centre for Contemporary Art, Roundhouse, English National Ballet, Manchester Int. Festival, Graeae Theatre, Young Vic, Cultural Olympiad, King's Cultural Institute, Southbank Centre, Liverpool Everyman and Playhouse"
and
"Alan Rusbridger, The Guardian, James Harding, The Times,Tony Gallagher, The Telegraph, Lord Black, Lionel Barber, Financial Times, Chris Blackhurst, The Independent,Peter Wright, Daily Mail,Sarah Sands, Evening Standard,Dominic Mohan, The Sun,Paul Ashford, The Express/The Star, John Witherow, Sunday Times, Lloyd Embley, Mirror and Sunday Mirror, Lord Hunt,Geordie Grieg, Mail on Sunday,John Mullin, Independent on Sunday, Ian MacGregor, Sunday Telegraph, John Micklethwait, The Economist, Fraser Nelson, The Spectator, Bob Satchwell, Society of Editors"
The former being a list of comma separated organisations and the latter a comma separated mix of organisations and their representatives.
