### ISSUE TITLE
Create React components for Header, Footer or Menu (you pick) 

### ISSUE THREAD

**Issue by elischutze** [HackBrexit/MinistersUnderTheInfluence#88]
Make a header for our demo mvp site
add footer/menus as you see fit

**Comment by aspiers** [comment]
Wasn't this closed by #91 or #101?

**Comment by charlottebrf** [comment]
@elischutze @cy0023 can i close this?

**Comment by aspiers** [comment]
I'm 99% sure this is done so closing - feel free to reopen if you disagree @elischutze @cy0023.
