### ISSUE TITLE
API required for 'data file'

### ISSUE THREAD

**Issue by Greatlemer** [HackBrexit/MinistersUnderTheInfluence#92]
### Description
We will need an API endpoint for the 'data file's that are being processed so that we can firstly check that we've not already processed a file and secondly update with information after we've processed a file.

#### Comments, Questions and Considerations
This is information that will need to be stored as well as exposed for the data processor to know what has been processed already, it will probably need to store the url of the file as well as the date the data was generated so we can compare to see if we have the file and also have the most up-to-date version of it.

### Acceptance Criteria
This story can be considered done when:
Given I have a file that has previously been processed
When I make a query for that file in the API
Then I'm returned a JSON response with the data regarding that file

Given I have a file that has not been processed previously
When I make a query for that file in the API
Then I'm returned a JSON response informing me the file cannot be found

Given I have a file that does not have an entry in the API
When I attempt to push data for that file to the API
Then the data is stored and can be returned later

**Comment by aspiers** [comment]
Should we also add this scenario?

Given I have a file that has previously been processed
When I attempt to push data for that file to the API
Then I'm returned a JSON response informing me the file is already there

**Comment by charlottebrf** [comment]
@aspiers @Greatlemer Can i close this now?

**Comment by aspiers** [comment]
I'm not sure but I expect @Greatlemer can answer this.

**Comment by aspiers** [comment]
#121 should address this, although I'm not sure if it covers all the test scenarios mentioned above.

**Comment by aspiers** [comment]
[The final scenario which I added](https://github.com/HackBrexit/MinistersUnderTheInfluence/issues/92#issuecomment-264333980) is not yet covered.
